[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundle = true

# Reroute price sync to the EDGE (Zero Runtime Minutes)
[[edge_functions]]
  path = "/api/getStocks"
  function = "getStocks"

# Standard Serverless Functions
[functions.dailyCron]
  schedule = "0 0 * * *"
